pipeline{

  agent any
  environment{
    VERSION = "${env.BUILD_ID}"
  }
  stages{
    stage('Code clone'){
      scripts{
      git branch: 'master', url:'https://github.com/Suresh-the1/Counter_application-main.git'
      }
    }
  }
}
